"""add payment status and real_delivery date

Revision ID: 58b8fdbe5f61
Revises: 0dd76f6f0d60
Create Date: 2026-05-12 05:08:53.229764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b8fdbe5f61'
down_revision: Union[str, Sequence[str], None] = '0dd76f6f0d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('real_delivery_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'real_delivery_date')
    # ### end Alembic commands ###
